<template><div><h1 id="create-a-simple-todo-list-api-using-fastapi" tabindex="-1"><a class="header-anchor" href="#create-a-simple-todo-list-api-using-fastapi" aria-hidden="true">#</a> Create A Simple Todo List API Using FastAPI</h1>
<h2 id="to-create-a-simple-to-do-list-api-using-fastapi-you-can-follow-these-steps" tabindex="-1"><a class="header-anchor" href="#to-create-a-simple-to-do-list-api-using-fastapi-you-can-follow-these-steps" aria-hidden="true">#</a> To create a simple to-do list API using FastAPI, you can follow these steps:</h2>
<h3 id="_1-install-fastapi-and-uvicorn-using-pip" tabindex="-1"><a class="header-anchor" href="#_1-install-fastapi-and-uvicorn-using-pip" aria-hidden="true">#</a> 1. Install FastAPI and uvicorn using pip:</h3>
<p>FastAPI is a Python web framework for building APIs, and uvicorn is an ASGI server for running Python web applications. The <code v-pre>pip</code> command is used to install these packages.</p>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>pip install fastapi uvicorn
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_2-create-a-new-python-file-and-import-the-necessary-fastapi-modules" tabindex="-1"><a class="header-anchor" href="#_2-create-a-new-python-file-and-import-the-necessary-fastapi-modules" aria-hidden="true">#</a> 2. Create a new Python file and import the necessary FastAPI modules:</h3>
<p>We import the <code v-pre>FastAPI</code> class from the <code v-pre>fastapi</code> module, and the <code v-pre>BaseModel</code> class from the <code v-pre>pydantic</code> module. <code v-pre>BaseModel</code> is used to define the structure of the to-do item.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> fastapi <span class="token keyword">import</span> FastAPI
<span class="token keyword">from</span> pydantic <span class="token keyword">import</span> BaseModel
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-define-a-class-to-represent-a-to-do-item-using-pydantic-s-basemodel-class" tabindex="-1"><a class="header-anchor" href="#_3-define-a-class-to-represent-a-to-do-item-using-pydantic-s-basemodel-class" aria-hidden="true">#</a> 3. Define a class to represent a to-do item using Pydantic's BaseModel class:</h3>
<p>We define a <code v-pre>TodoItem</code> class that inherits from <code v-pre>BaseModel</code>. The class has two attributes: <code v-pre>task</code>, which is a string representing the task to be done, and <code v-pre>completed</code>, which is a boolean indicating whether the task has been <code v-pre>completed</code> or not. The <code v-pre>completed</code> attribute has a default value of <code v-pre>False</code>.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">TodoItem</span><span class="token punctuation">(</span>BaseModel<span class="token punctuation">)</span><span class="token punctuation">:</span>
    task<span class="token punctuation">:</span> <span class="token builtin">str</span>
    completed<span class="token punctuation">:</span> <span class="token builtin">bool</span> <span class="token operator">=</span> <span class="token boolean">False</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_4-create-an-instance-of-the-fastapi-app" tabindex="-1"><a class="header-anchor" href="#_4-create-an-instance-of-the-fastapi-app" aria-hidden="true">#</a> 4. Create an instance of the FastAPI app:</h3>
<p>We create an instance of the <code v-pre>FastAPI</code> class and store it in the <code v-pre>app</code> variable.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>app <span class="token operator">=</span> FastAPI<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_5-create-an-empty-list-to-store-the-to-do-items" tabindex="-1"><a class="header-anchor" href="#_5-create-an-empty-list-to-store-the-to-do-items" aria-hidden="true">#</a> 5. Create an empty list to store the to-do items:</h3>
<p>We create an empty list named <code v-pre>todo_list</code> that will be used to store the to-do items.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>todo_list <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_6-define-a-route-to-create-a-new-to-do-item" tabindex="-1"><a class="header-anchor" href="#_6-define-a-route-to-create-a-new-to-do-item" aria-hidden="true">#</a> 6. Define a route to create a new to-do item:</h3>
<p>We use the <code v-pre>@app.post</code> decorator to define a route that handles HTTP POST requests to the <code v-pre>/todo/</code> endpoint. The <code v-pre>create_todo_item</code> function takes a single argument item of type <code v-pre>TodoItem</code>. The function appends the new to-do item to the <code v-pre>todo_list</code> and returns a JSON response with a success message.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token decorator annotation punctuation">@app<span class="token punctuation">.</span>post</span><span class="token punctuation">(</span><span class="token string">"/todo/"</span><span class="token punctuation">)</span>
<span class="token keyword">async</span> <span class="token keyword">def</span> <span class="token function">create_todo_item</span><span class="token punctuation">(</span>item<span class="token punctuation">:</span> TodoItem<span class="token punctuation">)</span><span class="token punctuation">:</span>
    todo_list<span class="token punctuation">.</span>append<span class="token punctuation">(</span>item<span class="token punctuation">)</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span><span class="token string">"message"</span><span class="token punctuation">:</span> <span class="token string">"Todo item created successfully"</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_7-define-a-route-to-get-all-the-to-do-items" tabindex="-1"><a class="header-anchor" href="#_7-define-a-route-to-get-all-the-to-do-items" aria-hidden="true">#</a> 7. Define a route to get all the to-do items:</h3>
<p>We use the <code v-pre>@app.get</code> decorator to define a route that handles HTTP GET requests to the <code v-pre>/todo/{item_index}</code> endpoint. The <code v-pre>get_todo_items</code> function returns a JSON response with the entire <code v-pre>todo_list</code>.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token decorator annotation punctuation">@app<span class="token punctuation">.</span>get</span><span class="token punctuation">(</span><span class="token string">"/todo/"</span><span class="token punctuation">)</span>
<span class="token keyword">async</span> <span class="token keyword">def</span> <span class="token function">get_todo_items</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span><span class="token string">"todo_list"</span><span class="token punctuation">:</span> todo_list<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_8-define-a-route-to-get-a-specific-to-do-item-by-its-index-in-the-list" tabindex="-1"><a class="header-anchor" href="#_8-define-a-route-to-get-a-specific-to-do-item-by-its-index-in-the-list" aria-hidden="true">#</a> 8. Define a route to get a specific to-do item by its index in the list:</h3>
<p>We use the <code v-pre>@app.get</code> decorator to define a route that handles HTTP GET requests to the <code v-pre>/todo/{item_index}</code> endpoint, where <code v-pre>item_index</code> is an integer representing the index of the to-do item in the <code v-pre>todo_list</code>. The <code v-pre>get_todo_item</code> function returns a JSON response with the to-do item at the specified index.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token decorator annotation punctuation">@app<span class="token punctuation">.</span>get</span><span class="token punctuation">(</span><span class="token string">"/todo/{item_index}"</span><span class="token punctuation">)</span>
<span class="token keyword">async</span> <span class="token keyword">def</span> <span class="token function">get_todo_item</span><span class="token punctuation">(</span>item_index<span class="token punctuation">:</span> <span class="token builtin">int</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> todo_list<span class="token punctuation">[</span>item_index<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_9-define-a-route-to-update-a-specific-to-do-item" tabindex="-1"><a class="header-anchor" href="#_9-define-a-route-to-update-a-specific-to-do-item" aria-hidden="true">#</a> 9. Define a route to update a specific to-do item:</h3>
<p>We use the <code v-pre>@app.put</code> decorator to define a route that handles HTTP PUT requests to the <code v-pre>/todo/{item_index}</code> endpoint. The <code v-pre>update_todo_item</code> function takes two arguments: <code v-pre>item_index</code>, which is an integer representing the index of the to-do item to be updated, and <code v-pre>item</code>, which is an instance of <code v-pre>TodoItem</code> representing the updated to-do item. The function updates the to-do item at the specified index in the <code v-pre>todo_list</code> and returns a JSON response with a success message.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token decorator annotation punctuation">@app<span class="token punctuation">.</span>put</span><span class="token punctuation">(</span><span class="token string">"/todo/{item_index}"</span><span class="token punctuation">)</span>
<span class="token keyword">async</span> <span class="token keyword">def</span> <span class="token function">update_todo_item</span><span class="token punctuation">(</span>item_index<span class="token punctuation">:</span> <span class="token builtin">int</span><span class="token punctuation">,</span> item<span class="token punctuation">:</span> TodoItem<span class="token punctuation">)</span><span class="token punctuation">:</span>
    todo_list<span class="token punctuation">[</span>item_index<span class="token punctuation">]</span> <span class="token operator">=</span> item
    <span class="token keyword">return</span> <span class="token punctuation">{</span><span class="token string">"message"</span><span class="token punctuation">:</span> <span class="token string">"Todo item updated successfully"</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_10-define-a-route-to-delete-a-specific-to-do-item" tabindex="-1"><a class="header-anchor" href="#_10-define-a-route-to-delete-a-specific-to-do-item" aria-hidden="true">#</a> 10. Define a route to delete a specific to-do item:</h3>
<p>We use the <code v-pre>@app.delete</code> decorator to define a route that handles HTTP DELETE requests to the <code v-pre>/todo/{item_index}</code> endpoint. The <code v-pre>delete_todo_item</code> function takes a single argument <code v-pre>item_index</code>, which is an integer representing the index of the to-do item to be deleted. The function deletes the to-do item at the specified index from the <code v-pre>todo_list</code> and returns a JSON response with a success message.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token decorator annotation punctuation">@app<span class="token punctuation">.</span>delete</span><span class="token punctuation">(</span><span class="token string">"/todo/{item_index}"</span><span class="token punctuation">)</span>
<span class="token keyword">async</span> <span class="token keyword">def</span> <span class="token function">delete_todo_item</span><span class="token punctuation">(</span>item_index<span class="token punctuation">:</span> <span class="token builtin">int</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">del</span> todo_list<span class="token punctuation">[</span>item_index<span class="token punctuation">]</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span><span class="token string">"message"</span><span class="token punctuation">:</span> <span class="token string">"Todo item deleted successfully"</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_11-run-the-application-using-uvicorn" tabindex="-1"><a class="header-anchor" href="#_11-run-the-application-using-uvicorn" aria-hidden="true">#</a> 11. Run the application using uvicorn:</h3>
<p>Finally, we use the <code v-pre>uvicorn</code> command to run the application on a local server. We pass the name of the Python file and the name of the <code v-pre>FastAPI</code> instance (<code v-pre>app</code>) as arguments to the <code v-pre>uvicorn.run</code> function, along with other optional parameters like <code v-pre>host</code> and <code v-pre>port</code>. By default, the application will run on <code v-pre>http://localhost:8000/</code>.</p>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>uvicorn main:app --reload
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>This is a basic example of how to create a to-do list API using FastAPI. You can customize it further to meet your requirements.</p>
</div></template>


