export const data = JSON.parse("{\"key\":\"v-1c936a17\",\"path\":\"/posts/moving-a-git-branch-to-a-new-base.html\",\"title\":\"Moving A Git Branch To A New Base\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Moving A Git Branch To A New Base\",\"author\":\"MinhTD\",\"description\":\"This blog shows how to move a Git branch to a new base using the git rebase command. The post explains how to use the git rebase --onto command to specify the base branch to move the work to and the point at which to snip the branch. The tutorial provides an example, showing how to move a branch named my-work from its original base branch old-home to a new base branch new-home. It also includes an alias command to make the process easier to remember and execute.\",\"tag\":[\"Git\"],\"category\":[\"Guide\"],\"date\":\"2023-04-21T00:00:00.000Z\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://minhtd18.github.io/posts/moving-a-git-branch-to-a-new-base.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Moving A Git Branch To A New Base\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This blog shows how to move a Git branch to a new base using the git rebase command. The post explains how to use the git rebase --onto command to specify the base branch to move the work to and the point at which to snip the branch. The tutorial provides an example, showing how to move a branch named my-work from its original base branch old-home to a new base branch new-home. It also includes an alias command to make the process easier to remember and execute.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"MinhTD\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Git\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-04-21T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Moving A Git Branch To A New Base\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-04-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"MinhTD\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.1,\"words\":629},\"filePathRelative\":\"posts/moving-a-git-branch-to-a-new-base.md\",\"localizedDate\":\"April 21, 2023\",\"excerpt\":\"<h1> Moving A Git Branch To A New Base</h1>\\n<p>Suppose you have some work on a git branch that you started from one branch, and you want to move that work to be based on a different branch, as if you had started from there originally. The git rebase command gives you the tools to do it, but it’s complicated, and I can never remember the details, so I finally figured it out and made an alias to do it.</p>\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
